# storage: /verdaccio/storage
storage: ./storage
store:
 s3-storage:
 bucket: BUCKET_NAME
 # keyPrefix: some-prefix # optional, has the effect of nesting all files in a subdirectory
 region: REGION # optional, will use aws s3's default behavior if not specified
 # endpoint: https://{service}.{region}.amazonaws.com # optional, will use aws s3's default behavior if not specified
 s3ForcePathStyle: false # optional, will use path style URLs for S3 objects
 accessKeyId: ACCESS_KEY # optional, aws accessKeyId for private S3 bucket
 secretAccessKey: SECRET_ACCESS_KEY # optional, aws secretAccessKey for private S3 bucket
listen:
 - 0.0.0.0:4873
# auth:
# gitlab:
# url: http://gitlab
uplinks:
 npmjs:
 url: https://registry.npmjs.org/
packages:
 '@*/*':
 # scoped packages
 access: $all
 publish: $authenticated
 proxy: npmjs
 gitlab: true
 '**':
 access: $all
 publish: $authenticated
 proxy: npmjs
 gitlab: true
logs:
 - { type: stdout, format: pretty, level: http }
 #- {type: file, path: verdaccio.log, level: info}
